# Generated by Django 5.1.1 on 2024-09-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_user_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
    ]
